spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true
  graphql:
    graphiql:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "info"